### ISSUE TITLE
Issues found while integrating in a test suite

### ISSUE THREAD

**Issue by nmav** [tomato42/tlsfuzzer#114]
As it is now including this test suite in an upstream project has some issues, which I'll try to summarize.
 * The output of the test suite is too verbose and it is hiding the actual failures. Running it provides several pages of output and in the end it prints something like:
```
Ran 65 scripts
good: 45
bad: 20
```
However, that summary isn't helpful. As an implementer I want to see what failed (and why). With that summary one has to go through many pages of output to see what failed. A better format of output is the one of automake's "make check".
```
test1 [PASS]
test2 [FAIL]
```
and test2.log will contain output to be checked.

 * Going through the output I see several failures as ```Alert description 49 != 50```. These seem like pedantic checks, but do not provide any information at all, i.e., why is this alert is expected not not the received? A flag ```-pendantic``` should be used to enable or disable such strictness.

 * Assertions are hard to trace back. The ```Alert description``` error described above traced back to a file but no line information was provided.

 * The input file contains all the tests an implementation must run. That works well, but is not future proof. Any tests added in the future will not be run by the test suite. That is quite important, as it indicates that this input file format is going to change in the future to address this, and thus prevents me from including that in a test suite.

**Comment by tomato42** [comment]
> As an implementer I want to see what failed (and why). 

yes, that's the goal, but we're rather far from it. Currently the tests are a disjoint set of scripts and as such the results represent that.

> With that summary one has to go through many pages of output to see what failed.

the script won't print any superfluous  output if everything went fine, see the travis runs for examples

then if one script is failing, you will see output related to just that failing script

in other words, the automated script approach is used for regression testing, not the initial test run - the initial run you have to do yourself, manually

> Going through the output I see several failures as Alert description 49 != 50. These seem like pedantic checks, but do not provide any information at all, i.e., why is this alert is expected not not the received? A flag -pendantic should be used to enable or disable such strictness.

for example, Client Key Exchange messages, or rather the key shares may be processed by the server only when it receives the CCS message, not right away when it receives the CKE message. That means the script/tlsfuzzer needs to send the CKE, CCS and Finished together. To detect error in parsing of malformed CKE message from unsuccessful negotiation of shared master secret, it needs to differentiate between illegal_parameter and bad_record_mac (as the first should come from malformed CKE while the other would come from Finished messages encrypted with unknown-to-server keys)

differences in the returned alert messages for different error conditions also allow for precise fingerprinting of server implementations: https://github.com/WestpointLtd/tls_prober

> Assertions are hard to trace back. The Alert description error described above traced back to a file but no line information was provided.

yes, I was thinking of adding ability to add names or comments to all generator or messages, with that name being part of failed assertion - given how the test scripts are constructed, saving the line in which the object was created is unlikely to be a clean solution... I've created #115 to track the former solution

> The input file contains all the tests an implementation must run. That works well, but is not future proof. Any tests added in the future will not be run by the test suite. That is quite important, as it indicates that this input file format is going to change in the future to address this, and thus prevents me from including that in a test suite.

This is just a stop-gap solution, not something that will morph into solution to #58. I would have no problem merging a PR that would double check if all scripts in `scripts/` are mentioned at least once in the provided json file though.

**Comment by nmav** [comment]
> >     Going through the output I see several failures as Alert description 49 != 50. These seem like pedantic checks, but do not provide any information at all, i.e., why is this alert is expected not not the received? A flag -pendantic should be used to enable or disable such strictness.
> 
> for example, Client Key Exchange messages, or rather the key shares may be processed by the server only when it receives the CCS message, not right away when it receives the CKE message. That means the script/tlsfuzzer needs to send the CKE, CCS and Finished together. To detect error in parsing of malformed CKE message from unsuccessful negotiation of shared master secret, it needs to differentiate between illegal_parameter and bad_record_mac (as the first should come from malformed CKE while the other would come from Finished messages encrypted with unknown-to-server keys)

That is one example where this makes sense not to be in a pedantic set. Serious errors should be given separately from warnings, in order to be able to start fixing the most serious issues first while ignoring the others, and then proceeding to less serious ones.
 
> differences in the returned alert messages for different error conditions also allow for precise fingerprinting of server implementations: https://github.com/WestpointLtd/tls_prober

That's a good reason it to put it in a separate pedantic set of tests. That's far from a vulnerability or something an implementor would be inclined to fix on the first run. Serious errors should take precedence.

> >     Assertions are hard to trace back. The Alert description error described above traced back to a file but no line information was provided.
> 
> yes, I was thinking of adding ability to add names or comments to all generator or messages, with that name being part of failed assertion - given how the test scripts are constructed, saving the line in which the object was created is unlikely to be a clean solution... I've created #115 to track the former solution

Thanks.

**Comment by tomato42** [comment]
there's another reason for expecting specific alert descriptions - to verify that all of the same kind of malformed messages receive the same alert description - something you won't catch if you ignore the descriptions completely, it's also something you can't do automatically in tlsfuzzer

that being said, I will accept PRs to other test scripts that change them in line with `test-dhe-rsa-key-exchange-with-bad-messages.py` (I mean the `-a` option), as long as we're changing the whole set of one type to other type...

while deciding severity of the issue is something that will need to happen (together with description of what the test really does, what the expected behaviour is, how the SUT is behaving, references to relevant RFC sections, etc.), it does have lower priority than, say, adding TLSv1.3, ECDSA or RSA-PSS support...

**Comment by tomato42** [comment]
@nmav I've created #115, #58 and #156, do you think that covers all enhancement suggestions, or should we add more?

**Comment by nmav** [comment]
I believe it is covered.
