### ISSUE TITLE
test-extended-master-secret-extension.py: doesn't accept -e

### ISSUE THREAD

**Issue by nmav** [tomato42/tlsfuzzer#119]
It seems that both ```test-extended-master-secret-extension.py``` and ```test-record-layer-fragmentation.py``` run all tests even if '-e' is specified. Thus at the moment to avoid known failures it has to be disabled.

**Comment by tomato42** [comment]
`test-record-layer-fragmentation.py` was fixed by #120

**Comment by nmav** [comment]
@tomato42 if you can address the test-extended-master-secret-extension.py would be great help. It would allow detecting any regressions on that code base (e.g., due to changes for TLS 1.3) easier.

**Comment by tomato42** [comment]
@nmav I'll try to get the blocking PR reviewed soon. Please ping me again if the merge of #121 doesn't happen by the end of the week.

**Comment by nmav** [comment]
@tomato42  It didn't!

**Comment by tomato42** [comment]
required something like 6 extra PRs merged but finally done 😄
