### ISSUE TITLE
ImportError from tlslite(-ng)

### ISSUE THREAD

**Issue by 0x64616E69656C** [tomato42/tlsfuzzer#13]
Hi,

I've tried running a few tests, resulting in the following error message:

```
daniel: ~/code/tlsfuzzer > PYTHONPATH=. python2.7 scripts/test-record-layer-fragmentation.py
Traceback (most recent call last):
  File "scripts/test-record-layer-fragmentation.py", line 8, in <module>
    from tlsfuzzer.runner import Runner
  File "/home/daniel/code/tlsfuzzer/tlsfuzzer/runner.py", line 7, in <module>
    from tlslite.messages import Message, Certificate
ImportError: No module named tlslite.messages
```

After trying ```sudo pip install tlslite```, I receive the following error message:

```
daniel: ~/code/tlsfuzzer > PYTHONPATH=. python2.7 scripts/test-record-layer-fragmentation.py
Traceback (most recent call last):
  File "scripts/test-record-layer-fragmentation.py", line 8, in <module>
    from tlsfuzzer.runner import Runner
  File "/home/daniel/code/tlsfuzzer/tlsfuzzer/runner.py", line 7, in <module>
    from tlslite.messages import Message, Certificate
ImportError: cannot import name Message
```

OS: Debian testing (x64_86)

Python2: ```Python 2.7.10+```

pip list:
```
argparse (1.2.1)
chardet (2.3.0)
colorama (0.3.3)
Cython (0.23.2)
distlib (0.2.1)
gmpy (1.17)
gmpy2 (2.0.7)
gyp (0.1)
html5lib (0.999)
pip (1.5.6)
pycrypto (2.6.1)
pycurl (7.19.5.1)
Pyste (0.9.10)
python-apt (1.0.1)
python-debian (0.1.27)
requests (2.8.1)
scapy (2.2.0)
scapy-ssl-tls (1.2.1)
setuptools (18.4)
six (1.10.0)
tlslite (0.4.9)
tlslite-ng (0.5.0)
urllib3 (1.12)
wfuzz (0.0.0)
wsgiref (0.1.2)
```

I'm not familiar with python, could you give me a hint?

Thanks!

**Comment by 0x64616E69656C** [comment]
Nevermind. I did a ```sudo pip uninstall tlslite tlslite-ng``` and a fresh ```sudo pip install --pre tlslite-ng``` as you stated on the openssl-dev ML, now it works.

**Comment by KincadePavich** [comment]
I am having an issue with the error "Cannot import name CertificateStauts" when I run "make test" after "make install." I tried uninstalling and reinstalling tlslite-ng as you said, but it did not fix the error. Also, when I run sudo commands with pip I get a message that says The directory ../home/kincade/.cache/pip/html or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want to use sudo's -H flag." I'm not quite sure what this means or what I should do. Any suggestions? Thank you.
