### ISSUE TITLE
test-chacha20.py: max size plaintext: incorrect assumptions on server behavior

### ISSUE THREAD

**Issue by nmav** [tomato42/tlsfuzzer#137]
The test 'max size plaintext' of test-chacha20.py assumes that the server will reply with a single application data message to its request. Snippet:
```
    node = node.add_child(ApplicationDataGenerator(data))
    node = node.add_child(ExpectApplicationData())
    node = node.add_child(AlertGenerator(AlertLevel.warning,
                                         AlertDescription.close_notify))
    node = node.add_child(ExpectAlert(AlertLevel.warning,
                                      AlertDescription.close_notify))
```

That expectation is arbitrary, and doesn't work in general. gnutls-serv for example will reply with a message forwarding the original request, and thus its reply will span across two Application data messages.

A better behavior would be to check the incoming queue for a close notify, and if it exists it should ignore anything else.

**Comment by tomato42** [comment]
actually we can wait for arbitrary number of Application Data records, please check #140

**Comment by nmav** [comment]
The patch addresses the issue.

**Comment by tomato42** [comment]
Thanks!
