### ISSUE TITLE
Don't expect server to support renegotiation_info if not required by testcase

### ISSUE THREAD

**Issue by savek-cc** [tomato42/tlsfuzzer#138]
The scripts often require the server to reply with a renegotiation_info extension in the server hello - even though something completely different shall be tested (e.g. scripts/test-invalid-content-type.py).
On a server that does not support re-negotiation at all, this extension won't be present - making all testcases fail.

**Comment by tomato42** [comment]
servers that don't do that, make the clients that use them vulnerable to the renegotiation attack

The empty renegotiation_info extension in the Server Hello _does not_ indicate that the server supports renegotiation. See [RFC 5746](https://tools.ietf.org/html/rfc5746) for details.

    If clients wish to ensure that such attacks are impossible, they need
    to terminate the connection immediately upon failure to receive the
    extension without completing the handshake.  Such clients MUST
    generate a fatal "handshake_failure" alert prior to terminating the
    connection.

**Comment by savek-cc** [comment]
That is true - but it's not something that should be a precondition for each and every testcase.
Why do we need to check if the server supports this extension if we want to test fragmentation?
The current behaviour thus just refuses to test the TLS implementation due to a missing extension.

**Comment by savek-cc** [comment]
P.S.:
```

   If a client offers the "renegotiation_info" extension or the
   TLS_EMPTY_RENEGOTIATION_INFO_SCSV SCSV and the server does not reply
   with "renegotiation_info" in the ServerHello, then this indicates
   that the server does not support secure renegotiation.  Because some
   attacks (see Section 1) look like a single handshake to the client,
   the client cannot determine whether or not the connection is under
   attack.  Note, however, that merely because the server does not
   acknowledge the extension does not mean that it is vulnerable; it
   might choose to reject all renegotiations and simply not signal it.
   However, it is not possible for the client to determine purely via
   TLS mechanisms whether or not this is the case.
```

**Comment by tomato42** [comment]
> That is true - but it's not something that should be a precondition for each and every testcase.
Why do we need to check if the server supports this extension if we want to test fragmentation?

Because it's expected that some servers require the client to advertise the secure renegotiation to allow connection in the first place (at the very least, apache with mod_nss does allow such configuration).

> However, it is not possible for the client to determine purely via
TLS mechanisms whether or not this is the case.

and that's the problem, and reason to require advertisement of the extension in every case, regardless if the renegotiation is actually supported

So, I either could parametrise all the test cases, and add a switch that will enable or disable advertisement and expecting of secure renegotiation extension from server, or I could expect that servers will actually implement an extension that is important for security 6 years after the relevant RFC was published...

**Comment by savek-cc** [comment]
The client sending the extension isn't the issue - it's just expecting the matching reply from the server for each and every usecase. If you just remove it from the expected server answer (except for one test that explicitly checks for support of this extension), it works fine with implementations not supporting re-negotiations (secure or otherwise).
My background is in embedded devices and those often use a very minimalistic TLS stack - not implementing any re-negotiation or other extensions for that matter.

**Comment by tomato42** [comment]
for tests that are completely unrelated to extensions and use just secure_renegotiation, yes, expectation from server could be removed

problem is, that there is no syntax to specify "this extension has to be there (e.g. extended_master_secret) while presence of this other one (e.g. secure_renegotiation) is optional" for more advanced test cases

I want to create a scanner of the server under test that will then configure the test case mutator to set the expected extensions or not based on actual features that the server has. But the tool is quite far from that now.
