### ISSUE TITLE
client_random always fixed to 00...00

### ISSUE THREAD

**Issue by savek-cc** [tomato42/tlsfuzzer#139]
In oder to have real client random, messages.py chould be changed:
```
diff --git a/tlsfuzzer/messages.py b/tlsfuzzer/messages.py
index 231b9d9..c5bb825 100644
--- a/tlsfuzzer/messages.py
+++ b/tlsfuzzer/messages.py
@@ -24,6 +24,7 @@ from tlslite.bufferedsocket import BufferedSocket
 from .handshake_helpers import calc_pending_states
 from .tree import TreeNode
 import socket
+import random
 
 
 class Command(TreeNode):
@@ -367,7 +368,7 @@ class ClientHelloGenerator(HandshakeProtocolMessageGenerator):
         if self.session_id is None:
             self.session_id = state.session_id
         if not state.client_random:
-            state.client_random = bytearray(32)
+            state.client_random = bytearray(random.getrandbits(8) for i in range(32))
 
         extensions = None
         if self.extensions is not None:
```

**Comment by tomato42** [comment]
this is done so the test cases are more deterministic

if that is to be changed, we need to be able to reply the conversation with the same random numbers, as such the test cases need to use a deterministic RNG and before using any values from that RNG, report the seed used

**Comment by savek-cc** [comment]
Background is to decode/decrypt captured data with wireshark - by using the NSS Key Log Format on the server side - here CLIENT_RANDOM is basically the (supposed to be unique) key that Wireshak (and other tools) use to match a key to a session.

**Comment by tomato42** [comment]
hmm, that indeed is a neat use case - for me it's easier to just fire up pdb to look at objects, but I can imagine that it's not particularly user friendly 😄 

If you combine the above patch with code that will create NSS key log format, I'll overlook the non-determinism of the test cases it creates 😉 but please use `getRandomBytes` from `tlslite/utils/cryptomath.py` as that will make it easier to change the code to the deterministic RNG later
