### ISSUE TITLE
AttributeError: 'Conversation' object has no attribute 'is_command'

### ISSUE THREAD

**Issue by omidraha** [tomato42/tlsfuzzer#16]
Run the `scripts/test-tls-server.py ` test, raise this error:
Also `sys` module that uses in this file, not imported.

	(env)$ PYTHONPATH=. python scripts/test-tls-server.py 
	Error encountered while processing node <tlsfuzzer.generators.Conversation object at 0x7f54e1451ed0> with last message being: None
	Traceback (most recent call last):
	  File "scripts/test-tls-server.py", line 27, in main
		res = runner.run()
	  File "..../github/tlsfuzzer/tlsfuzzer/runner.py", line 79, in run
		if node.is_command():
	AttributeError: 'Conversation' object has no attribute 'is_command'

	Test end
	successful: 0
	failed: 2

**Comment by tomato42** [comment]
that's a leftover from when I was trying a more top-down approach to programming tlsfuzzer, I'll remove it
