### ISSUE TITLE
common parameters  in json file

### ISSUE THREAD

**Issue by nmav** [tomato42/tlsfuzzer#187]
When adding a json file as:
```
[
    {"server_command": ["@SERVER@", "--http",
                 "--x509keyfile", "tests/serverX509Key.pem",
                 "--x509certfile", "tests/serverX509Cert.pem",
                 "--x509keyfile", "../../../certs/ecc256.pem",
                 "--x509certfile", "../../../certs/cert-ecc256.pem",
                 "--debug=3",
                 "--priority=@PRIORITY@",
                 "--disable-client-cert", "--port=4443"],
         {"name" : "test-ecdsa-sig-flexibility.py"},
         {"name" : "test-ocsp-stapling.py"}
...
```
trying to change it to use a different port is a tedious task. One would have to go through all elements and add an argument "-p portname". It would be nice if there were common parameters or if the "server_port" variable (read by the retention script) was read.

**Comment by Stonemason5040** [comment]
Should i make it so that i modify script_retention.py, then specifying --port argument in "server_commands" will be enough or will we use "common_arguments" in json files and then you would need to specify port for "server_command" as well as for "common_arguments"

**Comment by nmav** [comment]
Maybe Hubert has a better idea, but it may not be possible to deduce the port from `server_commands` (each server may have a different way to specify the port). As such specifying in two places may be the only way (that's still much better than specifying in all places).

**Comment by tomato42** [comment]
`server_command` should not be interpreted by the script, the port may not even be specified in it

we technically could reuse the `server_port` and `server_hostname` arguments, but those are special—the `scripts_retention.py` uses them to decide if the server is ready to accept connections from test scripts—so even if we use them to configure the scripts, by always passing them as `-p` and `-h`, we need the common arguments for `-n` and sometimes `-k` and `-c`

I would say that I prefer the explicit over implicit approach for this, that unfortunately means duplication of parameters.
(also, I think it will be more flexible once we start handling stuff that depends on DNS records, like HTTP/3, or other parts of PKI, like OCSP)
