### ISSUE TITLE
tlslite is required but is not a submodule

### ISSUE THREAD

**Issue by nmav** [tomato42/tlsfuzzer#216]
tlsfuzzer requires tlslite to be used. That however doesn't come as a submodule, and one has to download a recent tlslite in the tree. That results to an unclean tree:
```
	modified:   tlsfuzzer (untracked content)
```
which is particularly problematic when working with tlsfuzzer on another tree as a submodule like gnutls does.

A solution is to bring tlslite dependency as submodule to tlsfuzzer.

**Comment by tomato42** [comment]
tlsfuzzer is always tested against the newest (pre-)release of tlslite-ng, the idea being that tlslite-ng is installed in the system, the `PYTHONPATH=.` workflow is just a workaround for lack of ubiquity of `virtualenv`

**Comment by nmav** [comment]
I was unable to make PYTHONPATH work by pointing directly to dependencies. I think adding these two paths into .gitignore on master would be a good work-around.

**Comment by tomato42** [comment]
ok, if you would find such change helpful, I have nothing against merging such PR
