### ISSUE TITLE
TLS 1.3 unrecognized extensions

### ISSUE THREAD

**Issue by tomato42** [tomato42/tlsfuzzer#242]
verify that TLS 1.3 ClientHello with unrecognised extensions is still accepted and TLS 1.3 is negotiated.

Test especially if number 40 is included (the `extended_random`) and also other, higher in the list.

**Comment by NoName115** [comment]
I think we are already testing this type of conversation in https://github.com/tomato42/tlsfuzzer/issues/366, right?

**Comment by tomato42** [comment]
yes, `test-tls13-large-number-of-extensions.py` does test it already
