### ISSUE TITLE
Create wiki page that documents how to compile and start current versions of different servers

### ISSUE THREAD

**Issue by tomato42** [tomato42/tlsfuzzer#387]
# Feature request

## Is your feature request related to a problem? Please describe

It's not entirely obvious how to get OpenSSL, NSS, GnuTLS,... that supports TLS 1.3

## Describe the solution you'd like

wiki page that describes the repo locations, necessary configuration options and executable options used to start servers in TLS 1.3 mode

## Describe alternatives you've considered

linking to primary sources is probably ok, but having a one-page summary with copy-pastable links will ease work

**Comment by tomato42** [comment]
https://github.com/tomato42/tlsfuzzer/wiki/Server-setup

@nmav: r?
@Jakuje: r?

**Comment by nmav** [comment]
LGTM. The sections/subsections were not very distinguishable.

**Comment by Jakuje** [comment]
r+

**Comment by tomato42** [comment]
> The sections/subsections were not very distinguishable.

you mean that the subsections should have smaller headers?
