### ISSUE TITLE
TLS 1.3 HRR handshake, ClientHello shuffled extensions

### ISSUE THREAD

**Issue by tomato42** [tomato42/tlsfuzzer#398]
# New test script idea

## What TLS message this idea relates to?

ClientHello, HelloRetryRequest

## What TLS extension this idea relates to?

generally all ones

## What is the behaviour the test script should test?

check if the second client hello is rejected if the extensions are in different order than they were in the first ClientHello

also test with extension IDs that are still unassigned

## Are there scripts that test related functionality?

none

## Additional information

Test to verify if the server checks if the second ClientHello has minimal modifications to meet the requirements set in HelloRetryRequest

**Comment by nmav** [comment]
To add some context this test is about the https://tools.ietf.org/html/rfc8446#section-4.1.2 requirement:
```
The client will also send a
   ClientHello when the server has responded to its ClientHello with a
   HelloRetryRequest.  In that case, the client MUST send the same
   ClientHello without modification, except as follows:

   -  If a "key_share" extension was supplied in the HelloRetryRequest,
      replacing the list of shares with a list containing a single
      KeyShareEntry from the indicated group.

   -  Removing the "early_data" extension (Section 4.2.10) if one was
      present.  Early data is not permitted after a HelloRetryRequest.

   -  Including a "cookie" extension if one was provided in the
      HelloRetryRequest.

   -  Updating the "pre_shared_key" extension if present by recomputing
      the "obfuscated_ticket_age" and binder values and (optionally)
      removing any PSKs which are incompatible with the server's
      indicated cipher suite.

   -  Optionally adding, removing, or changing the length of the
      "padding" extension [RFC7685].

   -  Other modifications that may be allowed by an extension defined in
      the future and present in the HelloRetryRequest.
```

So that's a nice test to verify whether the server enforces that behavior (like tlslite-ng), but since the MUST is on the client to follow the rules, and not on the server to enforce, both behaviors are acceptable.

**Comment by tomato42** [comment]
while both behaviours are acceptable, we want secure and dependable behaviour in server when the protocol is underspecified, so the test should expect the server to detect this and abort appropriately
