### ISSUE TITLE
test-large-hello.py: adjust default min_ext to take new extensions into account

### ISSUE THREAD

**Issue by ElardusE** [tomato42/tlsfuzzer#413]
# Enhancement request

## Problem

TLS 1.3 added a bunch of extensions, up to 51, and the default 'min_ext' in this script is 50. Resulting in servers trying to interpret some of these random extensions (though also a test in itself, it is not the intension here).

## Suggested solution

Though one can use the switch '-m min-ext-no', the script should probably be enhanced to start at something above the highest current allocated number, which is 51. Say 55.

**Comment by tomato42** [comment]
the secondary purpose is to verify that implementation does not support any extensions not registered at IANA (especially ones right after official registrations), so using 52, being right after the last one negotiated would be correct

that being said, implementations should ignore 51 (keyshare) if there is no supported_versions (43) extensions so this current situation shouldn't cause problems...

**Comment by tomato42** [comment]
@ElardusE does #438 look good?

**Comment by ElardusE** [comment]
It does. Thanks.
