### ISSUE TITLE
dict is ordered in Python 3.7

### ISSUE THREAD

**Issue by tomato42** [tomato42/tlsfuzzer#418]
# Bug Report

## System Information

| Type                     | Version/Name |
| ------------------------ | ------------ |
| Operating System Name    |  n/a|
| Operating System Version |  n/a|
| Python version           |  3.7 |
| tlslite-ng version       |  0.8.0-alpha12 |
| tlsfuzzer revision       | 65af9ab3615a14 |

## Problem description

`tlslite-ng-random-subset.json` (and scripts in general) depend on the fact that dict() returns values in random order to select a random subset of tests when `-n` option is provided.

This feature won't work on Python 3.7 as the default dict preserves insertion order.

## Describe how to reproduce the problem

Steps to reproduce the behaviour:

1. Run script with large number of conversations (e.g. `test-tls13-finished.py`) with -n option multiple times on python 3.7

note that all conversations are always the same

## Expected behaviour

different set run on every run – the selected set and order of conversations should be random

## Additional context

https://mail.python.org/pipermail/python-dev/2017-December/151283.html

**Comment by tomato42** [comment]
It would be best to change from the straight `dict()` use and use some custom class (it can be a child of `dict()`) that would provide both randomised iteration and verify that newly added items don't overwrite old ones

**Comment by mildass** [comment]
Tried it in Python 2.7 and it runs same set for each run too. The only difference I see is order of values in `dict()` - in Python 3.7 order is how values have been inserted, otherwise the order is sorted other way (but the order is still same each run).

```
$ python2.7 scripts/test-tls13-finished.py -n 2
sanity ...
OK

single bit error - cipher TLS_AES_256_GCM_SHA384, bit 12 ...
OK

single bit error - cipher TLS_AES_256_GCM_SHA384, bit 13 ...
OK

sanity ...
OK

Fuzzing TLS 1.3 Finished messages
version: 3

Test end
successful: 4
failed: 0


$ python2 scripts/test-tls13-finished.py -n 3
sanity ...
OK

single bit error - cipher TLS_AES_256_GCM_SHA384, bit 12 ...   <--- as previous run
OK

single bit error - cipher TLS_AES_256_GCM_SHA384, bit 13 ...   <--- same one
OK

single bit error - cipher TLS_AES_256_GCM_SHA384, bit 10 ...
OK

sanity ...
OK

Fuzzing TLS 1.3 Finished messages
version: 3

Test end
successful: 5
failed: 0
```

Wouldn't be better replace `itertools.islice` for `random.sample` instead of creating custom class?

**Comment by tomato42** [comment]
> Wouldn't be better replace `itertools.islice` for `random.sample` instead of creating custom class?

it would be simpler, yes

**Comment by t184256** [comment]
@tomato42 I find you narrative on dict ordering somewhat misleading. That 'feature' was not a feature in the first place, and CPython 3.7 has the same behaviour as CPython 3.6 in this regard.

The previous unstable ordering was just an implementation detailed and it was not guaranteed to be random. CPython 3.6 brought a new, more performant, implementation that had a side effect of maintaining a meaningful dict order. GvR decided to promote that free bonus into a guarantee by Python 3.7. But, technically, CPython 3.7 brings no ordering changes to the dict implementation.

**Comment by tomato42** [comment]
yes, it wasn't a guarantee, but we did depend on it, it was a quick hack
