### ISSUE TITLE
test-fallback-scsv.py: assumes SSL 3.4 (TLS1.3) is not supported

### ISSUE THREAD

**Issue by nmav** [tomato42/tlsfuzzer#421]
# Bug Report
The script test-fallback-scsv.py: assumes SSL 3.4 (TLS1.3) is not supported.  For example test `record SSL3.4 hello SSL3.4` advertises SSL3.4 but expected SSL3.3 (TLS1.2) to be negotiated.

**Comment by tomato42** [comment]
as per [draft-28](https://tools.ietf.org/html/draft-ietf-tls-tls13-28#page-44):
```
   If this extension [supported_versions] is not present, servers which are compliant with
   this specification, and which also support TLS 1.2, MUST negotiate
   TLS 1.2 or prior as specified in [RFC5246], even if
   ClientHello.legacy_version is 0x0304 or later.  Servers MAY abort the
   handshake upon receiving a ClientHello with legacy_version 0x0304 or
   later.
```

**Comment by nmav** [comment]
The `--tls1.3` option fixes it for me, so closing.
