### ISSUE TITLE
test-tls13-finished.py: failed with unexpected NewSessionTicket

### ISSUE THREAD

**Issue by nmav** [tomato42/tlsfuzzer#431]
# Bug Report
The tests `padding - cipher TLS_AES_256_GCM_SHA384, pad_byte 0, pad_left 0, pad_right 16777167` and `padding - cipher TLS_AES_128_GCM_SHA256, pad_byte 0, pad_left 0, pad_right 16777183` fail with NewSessionTicket being received.

That is, with gnutls implementing the sending of new session tickets early:
https://gitlab.com/gnutls/gnutls/merge_requests/711

Output:
```
test-tls13-finished.py:stdout:padding - cipher TLS_AES_128_GCM_SHA256, pad_byte 0, pad_left 0, pad_right 16777183 ...
server:stderr:|<2>| added 3 protocols, 29 ciphersuites, 18 sig algos and 8 groups into priority list
server:stderr:|<3>| ASSERT: buffers.c[get_last_packet]:1172
server:stderr:|<2>| checking 13.01 (GNUTLS_AES_128_GCM_SHA256) for compatibility
server:stderr:|<3>| ASSERT: server_name.c[gnutls_server_name_get]:235
server:stderr:|<2>| Selected (RSA-PSS) cert based on ciphersuite 13.1: GNUTLS_AES_128_GCM_SHA256
server:stderr:|<2>| EXT[0x1ec6460]: server generated SECP256R1 shared key
...
server:stderr:Scheduling inactive connection for close
test-tls13-finished.py:stdout:Error encountered while processing node <tlsfuzzer.expect.ExpectClose object at 0x7fbd073df1d0> (child: None) with last message being: <tlslite.messages.Message object at 0x7fbd07395410>
test-tls13-finished.py:stdout:Error while processing
test-tls13-finished.py:stdout:Traceback (most recent call last):
test-tls13-finished.py:stdout:  File "scripts/test-tls13-finished.py", line 421, in main
test-tls13-finished.py:stdout:    runner.run()
test-tls13-finished.py:stdout:  File "/home/nmavrogi/cvs/gnutls/tests/suite/tls-fuzzer/tlsfuzzer/tlsfuzzer/runner.py", line 210, in run
test-tls13-finished.py:stdout:    RecordHeader2)))
test-tls13-finished.py:stdout:AssertionError: Unexpected message from peer: Handshake(new_session_ticket)
test-tls13-finished.py:stdout:
test-tls13-finished.py:stdout:padding - cipher TLS_AES_256_GCM_SHA384, pad_byte 0, pad_left 0, pad_right 16777167 ...
```

(the other case is identical)

What I see in wireshark (attached) is the server's part of the handshake, and the transfer of the packets from the client until a tcp session close. That seems to be exactly what the current code is supposed to handle, though that doesn't happen, and I'm not sure why.

[capture.zip](https://github.com/tomato42/tlsfuzzer/files/2222655/capture.zip)

**Comment by tomato42** [comment]
> That seems to be exactly what the current code is supposed to handle

actually, no, it's not; it is able to handle connection close + Alert message in queue, not connection close + NST + Alert

it probably can be implemented using ExpectNoMessage and ExpectNewSessionTicket as its sibling inserted after ExpectFinished in the test case

**Comment by tomato42** [comment]
I've updated the script in #437, but when running it against gnutls d59659792474abf I'm getting decryption failures  on the NewSessionTicket messages:
```
single bit error - cipher TLS_AES_128_GCM_SHA256, bit 131 ...
Error encountered while processing node ExpectNewSessionTicket() (child: ExpectNewSessionTicket()) with last message being: None
Error while processing
Traceback (most recent call last):
  File "scripts/test-tls13-finished.py", line 435, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 180, in run
    header, parser = self.state.msg_sock.recvMessageBlocking()
  File "/home/hkario/dev/tlsfuzzer/tlslite/messagesocket.py", line 101, in recvMessageBlocking
    for res in self.recvMessage():
  File "/home/hkario/dev/tlsfuzzer/tlslite/messagesocket.py", line 83, in recvMessage
    for ret in self.recvRecord():
  File "/home/hkario/dev/tlsfuzzer/tlslite/recordlayer.py", line 888, in recvRecord
    data = self._decryptAndUnseal(header, data)
  File "/home/hkario/dev/tlsfuzzer/tlslite/recordlayer.py", line 785, in _decryptAndUnseal
    raise TLSBadRecordMAC("Invalid tag, decryption failure")
TLSBadRecordMAC: Invalid tag, decryption failure
```

the test runs fine against current (as of 2018-07-26) NSS and openssl

**Comment by nmav** [comment]
Interesting. You are checking against the code that sends the session tickets after the client finished, so if you are sending a broken client finished I wouldn't have expected anything but an alert (which may be what you are getting as we didn't switch to the app keys early). Could you try the branch at this:
https://gitlab.com/gnutls/gnutls/merge_requests/711

**Comment by tomato42** [comment]
> which may be what you are getting as we didn't switch to the app keys early during handshake

ah, yes, that explains it; I've fixated myself on the ExpectNewSessionTicket when the tlsfuzzer doesn't really know what message it is receiving

**Comment by tomato42** [comment]
@nmav yes that gnutls#MR711 fixes issue of encryption, there's just minor issue of sending incorrect alert in case the Finished is really big:

```
padding - cipher TLS_AES_128_GCM_SHA256, pad_byte 0, pad_left 0, pad_right 16777183 ...
Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x7fd723e9acd0> (child: <tlsfuzzer.expect.ExpectClose object at 0x7fd723e9ac90>) with last message being: <tlslite.messages.Message object at 0x7fd723b69c50>
Error while processing
Traceback (most recent call last):
  File "scripts/test-tls13-finished.py", line 435, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 212, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1110, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "decode_error" does not match received "internal_error"
```

**Comment by nmav** [comment]
Nice, thank you!
