### ISSUE TITLE
Non-empty renegotiation_info in first ClientHello

### ISSUE THREAD

**Issue by tomato42** [tomato42/tlsfuzzer#531]
# New test script idea

## What TLS message this idea relates to?

ClientHello

## What TLS extension this idea relates to?

`renegotiation_info`

## What is the behaviour the test script should test?

Check if ClientHello is rejected if it includes `renegotiation_info` extension that is not empty in the first ClientHello.

Check both TLSv1.2 and TLSv1.3.

Also verify that the SCSV does not mask the extension being incorrect.

## Are there scripts that test related functionality?

There are multiple test with renegotiation, like `test-legacy-renegotiation.py`, but I don't think there's one specifically targetting `renegotiation_info` extension.

**Comment by The-Mule** [comment]
Did I get correctly that rejection should happen by handshake failure alert right after CH is sent? Quick testing reveals that openssl sends SH even with `TLSExtension(extType=ExtensionType.renegotiation_info).create(bytearray(b'\x00'))` sent in CH.

**Comment by tomato42** [comment]
well, the connection should probably be aborted by `illegal_parameter` (would have to refresh my memory of the RFC to be sure) rather than `handshake_failure`

OpenSSL replying to such extension is actually correct, by "empty" I meant, with empty `renegotiated_connection` string in the extension, given that it's defined as
```
      struct {
          opaque renegotiated_connection<0..255>;
      } RenegotiationInfo;
```
an extension with payload `\x00` is actually an "empty" `renegotiation_info` extension

see https://tools.ietf.org/html/rfc5746

**Comment by The-Mule** [comment]
> 3.4.  Client Behavior: Initial Handshake
> 
>   ... 
> 
>       *  If the extension is present, set the secure_renegotiation flag
>          to TRUE.  The client MUST then verify that the length of the
>          "renegotiated_connection" field is zero, and if it is not, MUST
>          abort the handshake (by sending a fatal handshake_failure
>          alert).

This this true for openssl and gnutls. NSS (on RHEL-7.6) sends `decode_error` instead.

**Comment by tomato42** [comment]
there may be filed a bug against NSS about that already, please check, if not, then create it

**Comment by The-Mule** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1600659. RFC is not 100% clear about this (see NSS bug for more detail).
