### ISSUE TITLE
tls13-record-layer-limits: incorrect padding

### ISSUE THREAD

**Issue by ElardusE** [tomato42/tlsfuzzer#545]
# Bug Report

## System Information

| Type                     | Version/Name |
| ------------------------ | ------------ |
| Python version           | 2.7.5 |
| tlslite-ng version       | 0.8.0-alpha26 |
| tlsfuzzer revision       | 0d16740957c5e59b41df451317bc56ad1248cdf6 |

## Problem description
Test: test-tls13-record-layer-limits.py

Problem 1
-----------
Sub test:
'max size of Finished msg, with 16587 bytes of record layer padding TLS_AES_128_GCM_SHA256'
Fails with:
AssertionError: Expected alert description "record_overflow" does not match received "unexpected_message"

A record of length 16640 is received in this test (including padding, content type and AEAD tag). This is a valid length, and hence the expected overflow alert is not observed.
This change to the test script does trigger the alert though, and causes the test to pass:
```
+        # 1 byte for message type
         # 1 byte for content type
         padding_size = 2**14 + 256 - 32 - 16 - 5
+        # 1 octet more than allowed
+        padding_size += 1
```
Problem 2:
-----------
Sub tests:
'too big plaintext, size: 2^14 - 8, with an additional 9 bytes of padding, cipher TLS_CHACHA20_POLY1305_SHA256'
'too big plaintext, size: 2^14 - 8, with an additional 9 bytes of padding, cipher TLS_CHACHA20_POLY1305_SHA256'
Fails with:
AssertionError: Unexpected message from peer: ApplicationData(len=276)

The plaintext length of 2^14 - 8 is within the limit of 2^14.
The length of  (2^14 - 8) + 9 padding + 1 content len + AEAD tag is also within the allowed length of 2^14 + 256.

The test expects an overflow alert, but it seems nothing is overflowing.

**Comment by tomato42** [comment]
> A record of length 16640 is received in this test (including padding, content type and AEAD tag). This is a valid length, and hence the expected overflow alert is not observed.

and

> The plaintext length of 2^14 - 8 is within the limit of 2^14.
The length of (2^14 - 8) + 9 padding + 1 content len + AEAD tag is also within the allowed length of 2^14 + 256.

while it's a valid length for a TLSCiphertext record, it decrypts to a plaintext that is longer than 2^14+1, which is invalid, and required to cause `record_overflow` alert to be sent

see [section 5.2](https://tools.ietf.org/html/rfc8446#section-5.2):
```
   An AEAD algorithm used in TLS 1.3 MUST NOT produce an expansion
   greater than 255 octets.  An endpoint that receives a record from its
   peer with TLSCiphertext.length larger than 2^14 + 256 octets MUST
   terminate the connection with a "record_overflow" alert.  This limit
   is derived from the maximum TLSInnerPlaintext length of 2^14 octets +
   1 octet for ContentType + the maximum AEAD expansion of 255 octets.
```

**Comment by ElardusE** [comment]
Missed the bit in Section 5.4.
Thank you.

**Comment by tomato42** [comment]
No problem, You're welcome
