### ISSUE TITLE
Improve testing of unique and well-known sig_algs in test-signature-algorithms.py

### ISSUE THREAD

**Issue by The-Mule** [tomato42/tlsfuzzer#558]
# New test script idea

## What TLS message this idea relates to?

ClientHello

## What TLS extension this idea relates to?

`signature_algorithms`

## What is the behaviour the test script should test?

Currently test is missing rsa_pss*, ed25519 and ed448 signature algorithms in "unique and well-known sig_algs, rsa_pss_rsae algorithms last" conversation. We need to make sure that when all ecdsa, dsa, rsa (with all md5, sha1, sha224, sha256, sha384 and sha512), all rsa_pss, ed25519 and ed448 are in `signature_algorithms` extension then they all can be used. In other words, when a server requires the one specified in the extension in the last place then ClientHello is not rejected. This should be tested for both TLS 1.2 and TLS 1.3 (in TLS 1.3 test script only ed25519 and ed448 need to be added I think).

## Are there scripts that test related functionality?

Yes, there is test-signature-algorithms.py and test-tls13-signature-algorithms.py, they only need to be slightly updated.

## Additional information

There are TLS implementations (namely NSS and gnutls) which have limited number of algorithms in `signature_algorithms` extension.

**Comment by EdgeKing810** [comment]
Can I take this? I'll submit a PR during the weekend.

**Comment by tomato42** [comment]
@EdgeKing810 there is PR#559 already filed, and it needs just few minor things to be fixed to be merge-able, so I think @The-Mule will want to finish it
