### ISSUE TITLE
run all script

### ISSUE THREAD

**Issue by rdp** [tomato42/tlsfuzzer#602]
# Feature request

It's confusing when I first install tlsfuzzer...if I'm not a "pro" which scripts should I run?
it would be convenient to have a "run all scripts" option somehow...

**Comment by tomato42** [comment]
Unfortunately the scripts in general do require good understanding of TLS and tested implementation, so unfortunately they are mostly for "pros".

Running all scripts is also counter-productive, as different scripts test different features, thus require different server configurations. They also commonly require customisation to pass (as multiple behaviours are allowed by the standard, the test needs to be told which behaviour should be expected from the server).

That being said, there is a way to execute all scripts against tlslite-ng server:
```
PYTHONPATH=. python tests/scripts_retention.py tests/tlslite-ng.json `which tls.py` 1850
```
so you can use that as a starting point (alternatively, you can take a look at how it's [integrated with GnuTLS](https://gitlab.com/gnutls/gnutls/tree/master/tests/suite/tls-fuzzer)). In general I'd suggest running the tests one by one, figuring out necessary options to make a given test pass and only then adding it to such a json file (i.e. use the automatic runner for regression testing not initial verification).

Also, while there are some scripts that can be used to check for [known vulnerabilities](https://github.com/tomato42/tlsfuzzer/wiki/Vulnerability-tests), that list is a). is not complete and b). the key word "known" is important: almost every script can discover a security vulnerability.

Finally, no, as it's stated in [VISION](https://github.com/tomato42/tlsfuzzer/blob/master/VISION.md) this is not the behaviour that we actually want of this framework. So if you have some suggestions for improvement that are not documented yet, then I'm open for discussing them.

**Comment by rdp** [comment]
OK thanks!
