### ISSUE TITLE
Inverse usage of -n option in the test scripts

### ISSUE THREAD

**Issue by tomato42** [tomato42/tlsfuzzer#608]
# Feature request

## Is your feature request related to a problem? Please describe
Integrating the test cases into upstream CI and keeping them updated is not a trivial task. One of the issues is figuring out how many examples (conversations) in every test case should be executed to balance the time of execution with test coverage.

Currently the `-n` option is used for this

## Describe the solution you'd like

The default for `-n` in a given test should be such that it executes in few seconds (less than 10 on mid-range CPU). Only when the user wants to execute all tests should the specification of `-n` option be necessary.

## Describe alternatives you've considered

Alternatively, a new option could be used, like `--ci`, that would perform the same task

## Additional context

needed for better integration of the tlsfuzzer with upstream test suites

Introducing an environment variable that can change the default (and set it to 0 to execute everything) could be reused for #187 to specify also server port or hostname

**Comment by tomato42** [comment]
@randombit 
Hi, I've noticed that in https://github.com/randombit/botan/commit/59e13d195b0ee76bc166504cdbed81a1243dd3f2 you are not executing some tests because they are very slow or because they test features not implemented in botan.

Are you aware of [scripts_retention.py](https://github.com/tomato42/tlsfuzzer/blob/master/tests/scripts_retention.py) and the example config files [tlslite-ng.json](https://github.com/tomato42/tlsfuzzer/blob/master/tests/tlslite-ng.json) and [tlslite-ng-random-subset.json](https://github.com/tomato42/tlsfuzzer/blob/master/tests/tlslite-ng-random-subset.json) for it?

Would the solution proposed in this bug help you execute all scripts always?

**Comment by randombit** [comment]
@tomato42 Thanks I wasn't aware of these. I'm not sure if they will help but I will investigate soon as improving our use of tlsfuzzer (and TLS-Attacker etc) is on the near term agenda for us.

**Comment by tomato42** [comment]
fixed by #646
