### ISSUE TITLE
Question about SLOTH Testing

### ISSUE THREAD

**Issue by matteotn** [tomato42/tlsfuzzer#664]
Hello,
i'm trying to reproduce a sloth vuln and i'm trying to check if it's sloth-vulnerable with your tool.

I'm seeing two scripts:

1. tls-certificate-verify.py, which is working fine
2. tls-rsa-sigs-on-certificate-verify.py which i don't know what it does. 

Checking the SLOTH paper, i found out there are two main attack vector:

1. Mutual Authentication attack vector;
2. ServerKeyExchange attack vector.

It seems like your tool is testing only the first one. Am I missing the right TLSFuzzer script to test ServerKeyExchange?
What does tls-rsa-sigs-on-certificate-verify.py tests? Reading the code, seems like it's testing various RSA signatures in a client authentication environment. 

Thank you for your time.

**Comment by tomato42** [comment]
It's possible to test signatures in ServerKeyExchange, the `test-sig-algs.py` and `test-signature-algorithms.py` can be used to verify if MD5 and (optionally SHA-1, see `--no-sha1` for the latter script) is not supported by the server

**Comment by matteotn** [comment]
> It's possible to test signatures in ServerKeyExchange, the `test-sig-algs.py` and `test-signature-algorithms.py` can be used to verify if MD5 and (optionally SHA-1, see `--no-sha1` for the latter script) is not supported by the server

Thank you, what about the `tls-rsa-sigs-on-certificate-verify`? what does it test?

**Comment by tomato42** [comment]
`tls-rsa-sigs-on-certificate-verify` essentially checks if server accepts signatures made with hash different than the PRF (with TLS 1.2 using either SHA-256 or SHA-384 PRF), including SHA-1.

If server has SHA-1 support disabled, tests that use it will fail.

**Comment by matteotn** [comment]
> It's possible to test signatures in ServerKeyExchange, the `test-sig-algs.py` and `test-signature-algorithms.py` can be used to verify if MD5 and (optionally SHA-1, see `--no-sha1` for the latter script) is not supported by the server

Just to be sure, what's the difference between `tls-sig-algs` and `test-signature-algorithms`? I want to be sure to use the right one.

>`tls-rsa-sigs-on-certificate-verify` essentially checks if server accepts signatures made with hash different than the PRF (with TLS 1.2 using either SHA-256 or SHA-384 PRF), including SHA-1.
If server has SHA-1 support disabled, tests that use it will fail.

Thank you for your clear reply.

**Comment by tomato42** [comment]
Hmm, actually `test-signature-algorithms` can be used only to verify that SHA-1 is disabled. To verify that server won't sign with MD5 you need to use `test-sig-algs.py` (specifically "MD5 first" and "MD5 first, no SHA-1") and `test-clienthello-md5.py`.

Though please note that this works only against servers with RSA certificates, only `test-signature-algorithms.py` was updated to support also ECDSA-using servers (if server has both cert types then both cert types need to be tested). 

You may also want to verify that the client can't force a legacy signature on TLS 1.3 server, that's in `test-tls13-pkcs-signature.py`.

**Comment by matteotn** [comment]
> Hmm, actually `test-signature-algorithms` can be used only to verify that SHA-1 is disabled.
> 
> Though please note that this works only against servers with RSA certificates, only `test-signature-algorithms.py` was updated to support also ECDSA-using servers (if server has both cert types then both cert types need to be tested).

you said I can't use `test-signature-algorithms` to check if a server is using MD5, which means ECDSA cannot be tested for MD5 signature, am i right? If I'm not mistaken, the second attack vector is related to MD5 signature only. it's okay to check if it's using SHA-1, but it's unnecessary in the context.

> You may also want to verify that the client can't force a legacy signature on TLS 1.3 server, that's in `test-tls13-pkcs-signature.py`.

That's useful, thank you.

**Comment by tomato42** [comment]
> you said I can't use `test-signature-algorithms` to check if a server is using MD5, which means ECDSA cannot be tested for MD5 signature, am i right?

not with current scripts, correct

>  If I'm not mistaken, the second attack vector is related to MD5 signature only. it's okay to check if it's using SHA-1, but it's unnecessary in the context.

yes, for server auth SLOTH just calls for disabling MD5

**Comment by matteotn** [comment]
Okay thank you for your time.

**Comment by matteotn** [comment]
Hello again!
i did implemented everything but i'm missing a fundamental part: somehow, all checks/sanity checks fails.


is it related to not supporting ECDSA?

the scripts:
`test-sig-algs.py`


 All checks fails with something like:

```
sanity ...
Error encountered while processing node <tlsfuzzer.expect.ExpectServerHello object at 0x7fc4b39b8fd0> (child: <tlsfuzzer.expect.ExpectCertificate object at 0x7fc4b3944048>) with last message being: <tlslite.messages.Message object at 0x7fc4b3956cf8>

Error while processing\
Traceback (most recent call last): 
File "tlsfuzzer/scripts/test-sig-algs.py", line 481, in main runner.run() 
File "tlsfuzzer/tlsfuzzer/runner.py", line 237, in run RecordHeader2)))
AssertionError: Unexpected message from peer: Alert(fatal, handshake_failure)

```
and `test-clienthello-md5.py` does the same but only for sanity checks.

Thanks

**Comment by tomato42** [comment]
> is it related to not supporting ECDSA?

not necessarily, `handshake_failure` is a generic "I can't negotiate mutually acceptable cryptographic algorithms", if `sanity` tests fail like that, then other tests results are not valid

it can fail because of ECDSA, or because the cipher suites enabled in the server don't match what the script advertises

`test-sig-algs.py` requires a server with a RSA certificate and  TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA or TLS_DHE_RSA_WITH_AES_128_CBC_SHA cipher suite enabled (`sanity` there advertises all valid algorithms, so that should not affect interoperability, unless the server is intolerant to rsa_pss signature algorithms)

`test-clienthello-md5.py` requires a server with a RSA certificate, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 cipher suite enabled and support for sha-1+rsa signature algorithm

**Comment by matteotn** [comment]
I've tested it on google.com
> `test-sig-algs.py` requires a server with a RSA certificate and TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA or TLS_DHE_RSA_WITH_AES_128_CBC_SHA cipher suite enabled (`sanity` there advertises all valid algorithms, so that should not affect interoperability, unless the server is intolerant to rsa_pss signature algorithms)

On google.com : TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA is supported, but it fails.

using nmap:


```
ssl-enum-ciphers: 
|   TLSv1.0: 
|     ciphers: 
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (prime256v1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (prime256v1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors: 
|       NULL
|     cipher preference: server
|     warnings: 
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|   TLSv1.1: 
|     ciphers: 
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (prime256v1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (prime256v1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors: 
|       NULL
|     cipher preference: server
|     warnings: 
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (prime256v1) - A
|       TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (prime256v1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (prime256v1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (prime256v1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (prime256v1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors: 
|       NULL
|     cipher preference: server
|     warnings: 
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|_  least strength: C

```


I'm assuming it's because they are using ECDSA Certificate.

Trying `nmap -sV --script ssl-cert -p 443 google.com | grep "Public Key type"`
the result is:
`| Public Key type: ec`

> `test-clienthello-md5.py` requires a server with a RSA certificate, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 cipher suite enabled and support for sha-1+rsa signature algorithm

This is not supported by google, no problem then.

**Comment by tomato42** [comment]
google.com tries to be "clever" about how it negotiates connections so it's a bad target to see how the tests behave

**Comment by matteotn** [comment]
> google.com tries to be "clever" about how it negotiates connections so it's a bad target to see how the tests behave

Okay, i tried with booking.com

```
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (prime256v1) - A
|       TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (prime256v1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (prime256v1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (prime256v1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (prime256v1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (prime256v1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (prime256v1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors: 
|       NULL
|     cipher preference: server
|     warnings: 
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|_  least strength: C
```
As you can see, it does support `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA`, but it shows the same Alert Message error.

**Comment by tomato42** [comment]
hmm, looks like it requires supported_groups for the ECDHE_RSA negotiation

**Comment by tomato42** [comment]
ok, #675 should make the test pass against booking.com (modulo support for rsa_pss_pss signatures)

**Comment by matteotn** [comment]
> ok, #675 should make the test pass against booking.com (modulo support for rsa_pss_pss signatures)

Yep it works now.  Thank you.
