### ISSUE TITLE
Tests fail if the Python interpreter binary isn't called "python"

### ISSUE THREAD

**Issue by airtower-luna** [tomato42/tlsfuzzer#670]
The command line built here will fail if there is no `python` binary in the path:
https://github.com/tomato42/tlsfuzzer/blob/f9d4439cd8b8e382fd0e9f2974036775e53d8fe8/tests/scripts_retention.py#L151

That is the case at least on Debian(-ish) systems with only Python 3 installed, where the interpreter is called `python3`. Is there any reason not to use [`sys.executable`](https://docs.python.org/3/library/sys.html#sys.executable) instead of a hardcoded name? It worked nicely for me at least, and I'd be happy to send a pull request.

**Comment by tomato42** [comment]
no, using `sys.executable` looks like a good idea

if you can, please send a PR
