### ISSUE TITLE
Duplicate Code fragment

### ISSUE THREAD

**Issue by Fantastic8** [tomato42/tlsfuzzer#684]
Hi, I think there is a duplicate code fragment in class ClientHelloGenerator at line 551 and line 554

https://github.com/tomato42/tlsfuzzer/blob/4b990ab73c4041dd2f6a6b8dd2b6b214e144841f/tlsfuzzer/messages.py#L551

**Comment by tomato42** [comment]
indeed there is, could you create a PR to fix it?
