### ISSUE TITLE
How to fix this "ModuleNotFoundError: No module named 'tlsfuzzer'"

### ISSUE THREAD

**Issue by sajualways** [tomato42/tlsfuzzer#692]
I get this below error when i try to execute below
python scripts/test-conversation.py
Traceback (most recent call last):
  File "scripts/test-conversation.py", line 11, in <module>
    from tlsfuzzer.runner import Runner
ModuleNotFoundError: No module named 'tlsfuzzer'

**Comment by tomato42** [comment]
run with specifying in environment where the modules can be found:
```
PYTHONPATH=. python scripts/test-conversation.py
```

**Comment by sajualways** [comment]
Thanks !
