### ISSUE TITLE
 Hello, I recently used the same script to test two different IP addresses. Both IPs have tls services, but the results of the test scripts are different. I don't understand the reasons for the different test results. In this respect, can you help me

### ISSUE THREAD

**Issue by higher75** [tomato42/tlsfuzzer#701]

**Comment by higher75** [comment]
One IP address is my own self-certificate generated by openssl, and the other IP address is purchased by me with money. What is the difference?

**Comment by tomato42** [comment]
there should be no difference, tlsfuzzer doesn't look at certificate, except to extract the public key to verify that the signatures on ServerKeyExchange int (TLS 1.2 and earlier) or CertificateVerify (in TLS 1.3) are correct.

what differences you see?

**Comment by higher75** [comment]
1. For example, when I run the script test-tls13- ccs.py If I run with a self signed IP, the result is:

Test end
====================
version: 3
====================
TOTAL: 3
SKIP: 0
PASS: 1
XFAIL: 0
FAIL: 2
XPASS: 0
====================
FAILED:
'CCS message after Finished message'
'sanity'
'sanity'

2. However, when I run with the service IP I purchased, the results are all failures. The results are as follows:

Test end
====================
version: 3
====================
TOTAL: 3
SKIP: 0
PASS: 0
XFAIL: 0
FAIL: 3
XPASS: 0
====================
FAILED:
'CCS message after Finished message'
'sanity'
'sanity'

**Comment by higher75** [comment]
Moreover, I don't quite understand one thing now. If you use tlsfuzzer to test the TLS service, how to determine that there is a problem with the TLS service. I think for a long time..... I don't understand that the successful running of these test files means that there is no problem with the TLS service, or the failure of the test means that there is no problem with the TLS service, so I want to ask you, thank you for your help

**Comment by tomato42** [comment]
> https://github.com/tomato42/tlsfuzzer/issues/701#issuecomment-694202425

if `sanity` test fails, then the results are invalid, you can't draw conclusions from them without looking at packet capture

> Moreover, I don't quite understand one thing now. If you use tlsfuzzer to test the TLS service, how to determine that there is a problem with the TLS service. I think for a long time..... I don't understand that the successful running of these test files means that there is no problem with the TLS service, or the failure of the test means that there is no problem with the TLS service, so I want to ask you, thank you for your help

the scripts verify if the server behaves in a way that's consistent with the relevant standards, in this case, that would be https://tools.ietf.org/html/rfc8446  - PASS means it behaves in RFC compliant manner, FAIL means it didn't, but again, this result is valid only if the `sanity` test passes

I suggest reading the documentation: https://tlsfuzzer.readthedocs.io/en/latest/theory.html

**Comment by higher75** [comment]
I compared the two clienthello messages sent, they are exactly the same, but one of the IP addresses will respond to the serverhello message, and the other will show that the handshake failed. I really don't understand why this happens..., my goodness...  ,This is my wireshark packet capture analysis... can you help me see it,

Secure Sockets Layer
    TLSv1.2 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: SSL 3.0 (0x0300)
        Length: 47
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 43
            Version: TLS 1.2 (0x0303)
            Random: 000000000000000000000000000000000000000000000000...
                GMT Unix Time: Jan  1, 1970 08:00:00.000000000 CST
                Random Bytes: 000000000000000000000000000000000000000000000000...
            Session ID Length: 0
            Cipher Suites Length: 4
            Cipher Suites (2 suites)
                Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
                Cipher Suite: TLS_EMPTY_RENEGOTIATION_INFO_SCSV (0x00ff)
            Compression Methods Length: 1
            Compression Methods (1 method)
                Compression Method: null (0)

**Comment by higher75** [comment]
And I found that if I use the IP address of the purchased ssl certificate, many scripts will appear handshake_failure... Thank you very much for your help

**Comment by tomato42** [comment]
do both servers have TLS_RSA_WITH_AES_128_CBC_SHA ciphersuite enabled? Which TLS implementation the servers are running? which version?

**Comment by higher75** [comment]
The first server with a self certificate selects TLS_ RSA_ WITH_ AES_ 128_ CBC_ SHA,tls1.2,

The second direct alert does not select any key suite,

Do you mean that  ....

Sorry, I don't quite understand what you mean

**Comment by tomato42** [comment]
> The second direct alert does not select any key suite,

that suggest that the second server has different configuration

**Comment by higher75** [comment]
What do different configurations mean? Can you give me a general description? I don't seem to know what different configurations mean,

**Comment by tomato42** [comment]
> What do different configurations mean? Can you give me a general description? I don't seem to know what different configurations mean,

something like this: https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslciphersuite

but I'm afraid that tlsfuzzer is still too unpolished for your use case; for now the intended audience are developers working on TLS implementations directly, i.e. developers of OpenSSL, GnuTLS, NSS, BoringSSL, etc.

**Comment by higher75** [comment]
Thank you very much for your help... I benefited a lot
