### ISSUE TITLE
Allow configurable port

### ISSUE THREAD

**Issue by nmav** [tomato42/tlsfuzzer#86]
Currently all tests utilize port 4433. When integrating that into a CI, it requires a system with port 4433 free, which may not be under the control of the runner. 

However, the important advantage of allowing a configurable port, is that tests requiring a different server (e.g., one verifying client certificates, one accepting them without verification, one which doesn't ask for a certificate), can be run independently and in parallel.

**Comment by tomato42** [comment]
most of the new tests accept `-p` parameter to change it (see `test-certificate-request.py` for an example) along with few other options

patches to convert other tests to do the same are welcome

**Comment by tomato42** [comment]
any specific tests that are missing this still?

**Comment by nmav** [comment]
I'll try to go through all tests failures in gnutls one of the next weeks. If any is related to port number I'll report it here.

**Comment by nmav** [comment]
I have not been able to run the server with alternative port.
Port 4433 is hardcoded almost everywhere in calls like wait_till_open().

In:
https://gitlab.com/gnutls/gnutls/tree/572ef411612091709aededb7444d3f41e853e061/tests/suite/ext-tests

the script ```tls-fuzzer-cert.sh``` will use a configuration with an alternative port. That fails with
```
server:stderr:HTTP Server listening on IPv6 :: port 5556...done
Traceback (most recent call last):
  File "tests/scripts_retention.py", line 201, in <module>
    main()
  File "tests/scripts_retention.py", line 185, in main
    good, bad = run_with_json(sys.argv[1], sys.argv[2])
  File "tests/scripts_retention.py", line 159, in run_with_json
    srv, srv_out, srv_err = start_server(command, environment)
  File "tests/scripts_retention.py", line 69, in start_server
    wait_till_open('localhost', 4433)
  File "tests/scripts_retention.py", line 54, in wait_till_open
    raise ValueError("Can't connect to server")
ValueError: Can't connect to server
```

**Comment by tomato42** [comment]
#118 should fix that
